name: phenopy_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - gdal=3.6.*
  - rasterio=1.3.*
  - geopandas=0.13.*
  - rioxarray=0.14.*
  - scikit-learn=1.2.*
  - numpy=1.23.*
  - pandas=1.5.*
  - matplotlib=3.6.*
  - joblib=1.2.*
